class CfgPatches
{
	class A3PL_Animations
	{
		requiredaddons[]={"A3_Anims_F"};
		requiredversion=0.1;
		units[]={};
		weapons[]={};
		magazines[]={};
	};
};
class CfgMovesBasic
{
	class ManActions
	{
		A3PL_EnteringCar="A3PL_EnteringCar";
		Gesture_drink=" ";
		Gesture_eat=" ";
		Gesture_key=" ";
		Gesture_restrain=" ";
		Gesture_holster=" ";
		Gesture_stop=" ";
		Gesture_throw=" ";
		Gesture_carry_box=" ";
		Gesture_golf=" ";
		Gesture_takehostage=" ";
		Gesture_takehostageloop=" ";
		Gesture_takehostageshootloop=" ";
		Gesture_wave=" ";
		Gesture_finger=" ";
		Gesture_watching=" ";
		Gesture_maskon=" ";
		Gesture_pickup=" ";
		Gesture_headswipe=" ";
	};
	class Actions
	{
		class NoActions: ManActions
		{
			Gesture_drink[]=
			{
				"Gesture_drink",
				"Gesture"
			};
			Gesture_eat[]=
			{
				"Gesture_eat",
				"Gesture"
			};
			Gesture_key[]=
			{
				"Gesture_key",
				"Gesture"
			};
			Gesture_restrain[]=
			{
				"Gesture_restrain",
				"Gesture"
			};
			Gesture_holster[]=
			{
				"Gesture_holster",
				"Gesture"
			};
			Gesture_stop[]=
			{
				"Gesture_stop",
				"Gesture"
			};
			Gesture_throw[]=
			{
				"Gesture_throw",
				"Gesture"
			};
			Gesture_takehostage[]=
			{
				"Gesture_takehostage",
				"Gesture"
			};
			Gesture_takehostageloop[]=
			{
				"Gesture_takehostageloop",
				"Gesture"
			};
			Gesture_takehostageshootloop[]=
			{
				"Gesture_takehostageshootloop",
				"Gesture"
			};
			Gesture_golf[]=
			{
				"Gesture_golf",
				"Gesture"
			};
			Gesture_carry_box[]=
			{
				"Gesture_carry_box",
				"Gesture"
			};
			Gesture_wave[]=
			{
				"Gesture_wave",
				"Gesture"
			};
			Gesture_finger[]=
			{
				"Gesture_finger",
				"Gesture"
			};
			Gesture_watching[]=
			{
				"Gesture_watching",
				"Gesture"
			};
			Gesture_maskon[]=
			{
				"Gesture_maskon",
				"Gesture"
			};
			Gesture_pickup[]=
			{
				"Gesture_pickup",
				"Gesture"
			};
			Gesture_headswipe[]=
			{
				"Gesture_headswipe",
				"Gesture"
			};
		};
	};
};
class CfgMovesMaleSdr: CfgMovesBasic
{
	skeletonName="OFP2_ManSkeleton";
	gestures="CfgGesturesMale";
	class States
	{
		class AmovPercMstpSnonWnonDnon;
		class CutSceneAnimationBase: AmovPercMstpSnonWnonDnon
		{
		};
		class A3PL_TakeHostage: CutSceneAnimationBase
		{
			file="\A3PL_animations\hostage\A3PL_TakeHostage.rtm";
			speed=0.30000001;
			looped=0;
			connectTo[]={};
			interpolateFrom[]={};
			interpolateTo[]={};
			disableWeapons=0;
			disableWeaponsLong=0;
			forceAim=1;
			showHandGun=1;
			canPullTrigger=1;
			showWeaponAim=1;
			canReload=1;
			WeaponIK=2;
			aiming="aimingPistol";
			aimingBody="aimingUpPistol";
		};
		class A3PL_TakenHostage: CutSceneAnimationBase
		{
			file="\A3PL_animations\hostage\A3PL_TakenHostage.rtm";
			speed=0.30000001;
			looped=0;
			connectTo[]={};
			interpolateFrom[]={};
			interpolateTo[]={};
			disableWeapons=0;
		};
		class A3PL_ReleaseHostage: CutSceneAnimationBase
		{
			file="\A3PL_animations\hostage\A3PL_ReleaseHostage.rtm";
			speed=0.30000001;
			looped=0;
			connectTo[]={};
			interpolateFrom[]={};
			interpolateTo[]={};
			disableWeapons=0;
			disableWeaponsLong=0;
			forceAim=1;
			showHandGun=1;
			canPullTrigger=1;
			showWeaponAim=1;
			canReload=1;
			WeaponIK=2;
			aiming="aimingPistol";
			aimingBody="aimingUpPistol";
		};
		class A3PL_ReleasedHostage: CutSceneAnimationBase
		{
			file="\A3PL_animations\hostage\A3PL_ReleasedHostage.rtm";
			speed=0.30000001;
			looped=0;
			connectTo[]={};
			interpolateFrom[]={};
			interpolateTo[]={};
			disableWeapons=0;
		};
		class A3PL_KneelToHandsUp: CutSceneAnimationBase
		{
			file="\A3PL_Police2\anims\KneelToHandsUp.rtm";
			speed=0.30000001;
			looped=0;
			connectTo[]={};
			interpolateFrom[]={};
			interpolateTo[]={};
			disableWeapons=0;
		};
		class A3PL_HandsupKneelKicked: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\KneelKickedDown.rtm";
			looped=0;
		};
		class A3PL_HandsupKneel: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\KneelHandsUp.rtm";
			looped=1;
		};
		class A3PL_HandsupKneelGetCuffed: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\KneelGettingCuffed.rtm";
			looped=0;
		};
		class A3PL_HandsupKneelCuffed: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\KneelCuffed.rtm";
			looped=1;
		};
		class A3PL_KickedDownLoop: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\KickedDownLoop.rtm";
			looped=1;
		};
		class A3PL_CuffKickDown: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\KickDownSomeone.rtm";
			looped=0;
		};
		class A3PL_IdleToHandsup: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\IdleToHandsup.rtm";
			looped=0;
		};
		class A3PL_HandsUpToKneel: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\HandsUpToKneel.rtm";
			looped=0;
		};
		class A3PL_HandsUp: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\HandsUp.rtm";
			looped=1;
		};
		class A3PL_Cuff: A3PL_KneelToHandsUp
		{
			file="\A3PL_Police2\anims\CuffingSomeone.rtm";
			looped=0;
		};
		class A3PL_Dance_Samba: CutSceneAnimationBase
		{
			file="\A3PL_Animations\anims\Samba.rtm";
			speed=0.0625;
			looped=1;
			connectTo[]={};
			interpolateFrom[]={};
			interpolateTo[]={};
			disableWeapons=0;
		};
		class A3PL_Dance_House1: CutSceneAnimationBase
		{
			file="\A3PL_Animations\anims\HouseDance1.rtm";
			speed=0.039999999;
			looped=1;
			connectTo[]={};
			interpolateFrom[]={};
			interpolateTo[]={};
			disableWeapons=0;
		};
		class A3PL_Golf_Drive: CutSceneAnimationBase
		{
			file="\A3PL_Animations\anims\Golf_Drive.rtm";
			speed=0.25;
			looped=0;
			connectTo[]={};
			interpolateFrom[]={};
			interpolateTo[]={};
			disableWeapons=0;
			forceAim=1;
			showHandGun=1;
			headBobMode=4;
			headBobStrength=-0.80000001;
		};
		class A3PL_Shovel_Dig: CutSceneAnimationBase
		{
			file="\A3PL_Animations\anims\Digging.rtm";
			speed=0.25;
			looped=1;
			connectTo[]={};
			interpolateFrom[]={};
			interpolateTo[]={};
			disableWeapons=0;
			forceAim=1;
			showHandGun=1;
			headBobMode=4;
			headBobStrength=-0.80000001;
		};
		class A3PL_EnteringCar: AmovPercMstpSnonWnonDnon
		{
			variantsPlayer[]={};
			file="\A3PL_Animations\anims\Entering_Car.rtm";
			speed=0.25;
			looped=0;
			soundOverride="Walk";
			disableWeapons=0;
			enableOptics=0;
			leaningFactorBeg=0;
			ConnectTo[]=
			{
				"AmovPercMstpSnonWnonDnon",
				0.02
			};
			InterpolateTo[]=
			{
				"Unconscious",
				0.1
			};
			headBobMode=4;
			headBobStrength=-0.80000001;
		};
	};
};
class CfgGesturesMale
{
	skeletonName="OFP2_ManSkeleton";
	class ManActions
	{
	};
	class Actions
	{
		class NoActions
		{
			turnSpeed=0;
			upDegree=0;
			limitFast=1;
			useFastMove=0;
		};
	};
	class Default
	{
		actions="NoActions";
		file="";
		looped=1;
		speed=0.5;
		static=0;
		relSpeedMin=1;
		relSpeedMax=1;
		soundEnabled=0;
		soundOverride="";
		soundEdge[]={0.5,1};
		terminal=0;
		ragdoll=0;
		equivalentTo="";
		connectAs="";
		connectFrom[]={};
		connectTo[]={};
		interpolateWith[]={};
		interpolateTo[]={};
		interpolateFrom[]={};
		mask="empty";
		interpolationSpeed=6;
		interpolationRestart=0;
		preload=0;
		disableWeapons=1;
		enableOptics=0;
		showWeaponAim=1;
		enableMissile=1;
		enableBinocular=1;
		showItemInHand=0;
		showItemInRightHand=0;
		showHandGun=0;
		canPullTrigger=1;
		Walkcycles=1;
		headBobMode=0;
		headBobStrength=0;
		leftHandIKBeg=0;
		leftHandIKEnd=0;
		rightHandIKBeg=0;
		rightHandIKEnd=0;
		leftHandIKCurve[]={1};
		rightHandIKCurve[]={1};
		forceAim=0;
	};
	class States
	{
		class Gesture_drink: Default
		{
			file="\A3PL_animations\anims\Drinking.rtm";
			looped=0;
			speed=0.1;
			mask="drink_blend";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_eat: Default
		{
			file="\A3PL_animations\anim_eating.rtm";
			looped=0;
			speed=0.30000001;
			mask="eat_blend";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_key: Default
		{
			file="\A3PL_animations\anim_key.rtm";
			looped=0;
			speed=0.69999999;
			mask="a3pl_right_arm";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_restrain: Default
		{
			file="\A3PL_animations\anim_restrain.rtm";
			looped=1;
			speed=0.30000001;
			mask="eat_blend";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_holster: Default
		{
			file="\A3PL_animations\anim_holster.rtm";
			looped=1;
			speed=0.30000001;
			mask="a3pl_right_arm";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_stop: Default
		{
			file="";
			looped=0;
			speed=0.30000001;
			mask="";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_throw: Default
		{
			file="\A3PL_animations\anim_throw.rtm";
			looped=0;
			speed=1.7;
			mask="a3pl_right_arm";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_carry_box: Default
		{
			file="\A3PL_animations\anim_carry_box.rtm";
			looped=1;
			speed=1;
			mask="carry_blend";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class gesture_takehostage: Default
		{
			file="\A3PL_animations\hostage\A3PL_TakeHostage.rtm";
			looped=0;
			speed=0.30000001;
			mask="golf_blend";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
			canPullTrigger=1;
			canReload=0;
			forceAim=1;
			disableWeapons=0;
			showHandGun=1;
		};
		class gesture_takehostageloop: Default
		{
			file="\A3PL_animations\hostage\A3PL_TakeHostageLoop.rtm";
			looped=1;
			speed=1;
			mask="golf_blend";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
			canPullTrigger=1;
			canReload=0;
			forceAim=1;
			disableWeapons=0;
			showHandGun=1;
		};
		class gesture_takehostageshootloop: Default
		{
			file="\A3PL_animations\hostage\A3PL_TakeHostageShootLoop.rtm";
			looped=1;
			speed=1;
			mask="golf_blend";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
			canPullTrigger=1;
			canReload=0;
			forceAim=1;
			disableWeapons=0;
			showHandGun=1;
		};
		class Gesture_golf: Default
		{
			file="\A3PL_animations\anim_golf.rtm";
			looped=1;
			speed=1;
			mask="golf_blend";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_wave: Default
		{
			file="\A3PL_animations\anim_wave.rtm";
			looped=0;
			speed=0.60000002;
			mask="a3pl_right_arm";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_finger: Default
		{
			file="\A3PL_animations\anim_finger.rtm";
			looped=0;
			speed=0.60000002;
			mask="a3pl_right_arm";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_watching: Default
		{
			file="\A3PL_animations\anim_watching.rtm";
			looped=0;
			speed=1.4;
			mask="a3pl_right_arm";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_maskon: Default
		{
			file="\A3PL_animations\anim_maskon.rtm";
			looped=0;
			speed=0.40000001;
			mask="eat_blend";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_Pickup: Default
		{
			file="\A3PL_animations\anim_pickup.rtm";
			looped=0;
			speed=0.40000001;
			mask="a3pl_right_arm";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
		class Gesture_Headswipe: Default
		{
			file="\A3PL_animations\anim_headswipe.rtm";
			looped=0;
			speed=0.40000001;
			mask="a3pl_right_arm";
			rightHandIKCurve[]={0,0,0,0,0,0,0,0};
			leftHandIKCurve[]={0,0,0,0,0,0,0,0};
		};
	};
	class BlendAnims
	{
		golf_blend[]=
		{
			"weapon",
			1,
			"head",
			1,
			"Spine",
			1,
			"Spine1",
			1,
			"Spine2",
			1,
			"Spine3",
			1,
			"LeftArm",
			1,
			"LeftShoulder",
			1,
			"RightShoulder",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1
		};
		hostageshoot_blend[]=
		{
			"head",
			1,
			"LeftUpLeg",
			1,
			"RightUpLeg",
			1,
			"LeftUpLegRoll",
			1,
			"RightUpLegRoll",
			1,
			"Spine",
			1,
			"Spine1",
			1,
			"Spine2",
			1,
			"Spine3",
			1,
			"LeftArm",
			1,
			"LeftShoulder",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1
		};
		carry_blend[]=
		{
			"Spine2",
			1,
			"Spine3",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1
		};
		drink_blend[]=
		{
			"neck",
			1,
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"RightHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1
		};
		a3pl_right_arm[]=
		{
			"Spine2",
			1,
			"RightShoulder",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1
		};
		a3pl_throw_blend[]=
		{
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1,
			"RightShoulder",
			1
		};
		eat_blend[]=
		{
			"LeftArm",
			1,
			"LeftArmRoll",
			1,
			"LeftForeArm",
			1,
			"LeftForeArmRoll",
			1,
			"LeftHand",
			1,
			"LeftHandRing",
			1,
			"LeftHandPinky1",
			1,
			"LeftHandPinky2",
			1,
			"LeftHandPinky3",
			1,
			"LeftHandRing1",
			1,
			"LeftHandRing2",
			1,
			"LeftHandRing3",
			1,
			"LeftHandMiddle1",
			1,
			"LeftHandMiddle2",
			1,
			"LeftHandMiddle3",
			1,
			"LeftHandIndex1",
			1,
			"LeftHandIndex2",
			1,
			"LeftHandIndex3",
			1,
			"LeftHandThumb1",
			1,
			"LeftHandThumb2",
			1,
			"LeftHandThumb3",
			1,
			"RightArm",
			1,
			"RightArmRoll",
			1,
			"RightForeArm",
			1,
			"RightForeArmRoll",
			1,
			"RightHand",
			1,
			"RightHandRing",
			1,
			"RightHandPinky1",
			1,
			"RightHandPinky2",
			1,
			"RightHandPinky3",
			1,
			"RightHandRing1",
			1,
			"RightHandRing2",
			1,
			"RightHandRing3",
			1,
			"RightHandMiddle1",
			1,
			"RightHandMiddle2",
			1,
			"RightHandMiddle3",
			1,
			"RightHandIndex1",
			1,
			"RightHandIndex2",
			1,
			"RightHandIndex3",
			1,
			"RightHandThumb1",
			1,
			"RightHandThumb2",
			1,
			"RightHandThumb3",
			1
		};
	};
};
