class CfgSurfaces {
	class Default {};
	class cype_grass : Default {
		files = "fishers_grass_*";
		character = "KLGrass1";
		soundEnviron = "grass";
		soundHit = "soft_ground";
		impact = "hitGroundSoft";
		rough = 0.079999998;
		maxSpeedCoef = 0.89999998;
		dust = 0.15000001;
		lucidity = 1.25;
		grassCover = 0.40000001;
		maxClutterColoringCoef = 1.35;
	};
	class cype_forest : Default {
		files = "fishers_forest_*";
		character = "KLForestCon";
		soundEnviron = "forest_exp";
		soundHit = "soft_ground";
		impact = "hitGroundSoft";
		rough = 0.079999998;
		maxSpeedCoef = 0.89999998;
		dust = 0.1;
		lucidity = 4;
		grassCover = 0.5;
		maxClutterColoringCoef = 1.35;
		AIAvoidStance = 2;
	};
	class cype_soil : Default {
		files = "fishers_soil_*";
		character = "KLSoil";
		soundEnviron = "dirt";
		soundHit = "soft_ground";
		rough = 0.15000001;
		maxSpeedCoef = 0.85000002;
		dust = 0.050000001;
		lucidity = 1.5;
		grassCover = 0;
		impact = "hitGroundHard";
		surfaceFriction = 1.7;
		maxClutterColoringCoef = 1.2;
	};
	class cype_seabed : Default {
		files = "fishers_seabed_*";
		character = "Empty";
		soundEnviron = "sand_exp";
		soundHit = "soft_ground";
		rough = 0.1;
		maxSpeedCoef = 0.885;
		dust = 0.5;
		lucidity = 1.25;
		grassCover = 0.0;
		maxClutterColoringCoef = 1.5;
		impact = "hitGroundSoft";
		surfaceFriction = 1.6;
	};
	class cype_beach : Default {
		files = "fishers_beach_*";
		character = "Empty";
		soundEnviron = "sand_exp";
		soundHit = "soft_ground";
		rough = 0.1;
		maxSpeedCoef = 0.885;
		dust = 0.5;
		lucidity = 1.25;
		grassCover = 0.0;
		maxClutterColoringCoef = 1.5;
		impact = "hitGroundSoft";
		surfaceFriction = 1.6;
	};
	class cype_plowedfield : Default {
		files = "fishers_plowedfield_*";
		character = "Empty";
		soundEnviron = "dirt";
		soundHit = "soft_ground";
		rough = 0.15000001;
		maxSpeedCoef = 0.85000002;
		dust = 0.050000001;
		lucidity = 1.5;
		grassCover = 0;
		impact = "hitGroundHard";
		surfaceFriction = 1.7;
		maxClutterColoringCoef = 1.2;
	};
	class cype_Dark_Pavement : Default {
		files = "fishers_dark_pavement_*";
		character = "Empty";
		soundEnviron = "concrete";
		soundHit = "concrete";
		rough = 0.050000001;
		maxSpeedCoef = 1;
		dust = 0.050000001;
		lucidity = 0.30000001;
		grassCover = 0;
		impact = "hitConcrete";
		maxClutterColoringCoef = 1;
	};
	class cype_concrete : Default {
		files = "fishers_conc_*";
		character = "Empty";
		soundEnviron = "concrete";
		soundHit = "concrete";
		rough = 0.050000001;
		maxSpeedCoef = 1;
		dust = 0.050000001;
		lucidity = 0.30000001;
		grassCover = 0;
		impact = "hitConcrete";
		maxClutterColoringCoef = 1;
	};
	class cype_mud : Default {
		//access = 0;
		files = "gdt_mud_*";
		character = "Empty";
		soundEnviron = "gravel";
		soundHit = "soft_ground";
		impact = "hitGroundSoft";
		rough = 0.2;
		maxSpeedCoef = 0.94999999;
		dust = 0.2;
		lucidity = 0.30000001;
		grassCover = 0;
		maxClutterColoringCoef = 1.15;
	};
	class cype_dirt : Default {
		//access = 0;
		files = "gdt_dirt_*";
		character = "GrassDryClutter";
		soundEnviron = "dirt";
		soundHit = "hard_ground";
		rough = 0.09;
		maxSpeedCoef = 0.9;
		dust = 0.5;
		lucidity = 1;
		grassCover = 0.03;
		impact = "hitGroundSoft";
		surfaceFriction = 1.8;
		maxClutterColoringCoef = 1.35;
	};
};