class CfgPatches
{
	class SMA_MK18
	{
		requiredaddons[]=
		{
			"A3PL_Cars"
		};
		requiredversion=0.1;
		units[]={};
		weapons[]=
		{
			"SMA_MK18afg",
			"SMA_MK18_BASE",
			"SMA_MK18afg_SM",
			"SMA_MK18afgBLK",
			"SMA_MK18afgODBLK",
			"SMA_MK18afgBLK_SM",
			"SMA_MK18afgODBLK_SM",
			"SMA_MK18afgOD",
			"SMA_MK18afgOD_SM",
			"SMA_MK18afgTAN",
			"SMA_MK18afgTAN_SM",
			"SMA_MK18afgTANBLK",
			"SMA_MK18afgTANBLK_SM",
			"SMA_MK18MOE",
			"SMA_MK18MOE_SM",
			"SMA_MK18MOETAN",
			"SMA_MK18MOETAN_SM",
			"SMA_MK18MOEBLK",
			"SMA_MK18MOEBLK_SM",
			"SMA_MK18MOEODBLK",
			"SMA_MK18MOEODBLK_SM",
			"SMA_MK18MOEOD",
			"SMA_MK18MOEOD_SM",
			"SMA_MK18MOEBLKTAN",
			"SMA_MK18MOEBLKTAN_SM",
			"SMA_MK18_GL",
			"SMA_MK18_GL_SM",
			"SMA_MK18TANBLK_GL",
			"SMA_MK18TANBLK_GL_SM",
			"SMA_MK18TAN_GL",
			"SMA_MK18TAN_GL_SM",
			"SMA_MK18BLK_GL",
			"SMA_MK18BLK_GL_SM",
			"SMA_MK18ODBLK_GL",
			"SMA_MK18ODBLK_GL_SM",
			"SMA_MK18OD_GL",
			"SMA_MK18OD_GL_SM"
		};
		author="Specialist Military Arms";
	};
};
class asdg_OpticRail1913;
class asdg_FrontSideRail;
class CfgWeapons
{
	class Rifle;
	class ItemCore;
	class InventoryOpticsItem_Base_F;
	class InventoryFlashLightItem_Base_F;
	class InventoryMuzzleItem_Base_F;
	class GrenadeLauncher;
	class UGL_F: GrenadeLauncher
	{
		class Single;
	};
	class mk20_base_f;
	class SMA_AssaultBase: mk20_base_f
	{
		class WeaponSlotsInfo;
	};
	class SMA_556_RIFLEBASE: SMA_AssaultBase
	{
		class Single;
		class FullAuto;
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class PointerSlot;
			class MuzzleSlot;
		};
	};
	class SMA_762_RIFLEBASE: SMA_AssaultBase
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class MuzzleSlot;
			class CowsSlot;
			class PointerSlot;
		};
		class Single;
		class FullAuto;
	};
	class SMA_MK18_BASE: SMA_556_RIFLEBASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]+=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
		};
		scope=1;
		dlc="SMA";
		inertia=0.44999999;
		recoil="recoil_car";
		author="Specialist Military Arms";
		drysound[]=
		{
			"A3LL_Tommy\data\MK18\Mainempty1",
			1.5,
			1,
			10
		};
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL5.ogg",
			1,
			1,
			35
		};
		changeFiremodeSound[]=
		{
			"A3LL_Tommy\data\MK18\clickmk18.ogg",
			0.25118899,
			1,
			20
		};
		opticsZoomMin=0.375;
		opticsZoomMax=1.1;
		opticsZoomInit=0.75;
		discreteDistance[]={100,200,300,400,500,600};
		descriptionShort="5.56mm Assault Rifle";
		reloadaction="GestureReloadSPAR_01";
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		class Single: Single
		{
			scope=2;
			dispersion=0.00058180001;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class SilencedSound
			{
				soundSet="";
				soundSetShot[]=
				{
					"SMA_MK18_SilencerShot_Soundset",
					"TRG20_silencerTail_SoundSet",
					"TRG20_silencerInteriorTail_SoundSet"
				};
			};
			class StandardSound
			{
				soundSet="";
				soundSetShot[]=
				{
					"SMA_MK18_Shot_Soundset",
					"TRG20_Tail_SoundSet",
					"TRG20_InteriorTail_SoundSet"
				};
			};
		};
		class FullAuto: FullAuto
		{
			reloadTime=0.071125001;
			dispersion=0.00058180001;
			sounds[]=
			{
				"StandardSound",
				"SilencedSound"
			};
			class SilencedSound
			{
				soundSet="";
				soundSetShot[]=
				{
					"SMA_MK18_SilencerShot_Soundset",
					"TRG20_silencerTail_SoundSet",
					"TRG20_silencerInteriorTail_SoundSet"
				};
			};
			class StandardSound
			{
				soundSet="";
				soundSetShot[]=
				{
					"SMA_MK18_Shot_Soundset",
					"TRG20_Tail_SoundSet",
					"TRG20_InteriorTail_SoundSet"
				};
			};
		};
	};
	class SMA_MK18afg: SMA_MK18_BASE
	{
		scope=2;
		displayName="MK18 MOD1(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afg.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_co.paa",
			"\A3LL_Tommy\data\afg_black_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\magnoalpha_black_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afg_ca.paa";
	};
	class SMA_MK18afg_SM: SMA_MK18_BASE
	{
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afgSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_co.paa",
			"\A3LL_Tommy\data\afg_black_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\clip_diffuse1.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgSM_ca.paa";
	};
	class SMA_MK18afgBLK: SMA_MK18_BASE
	{
		scope=2;
		displayName="MK18 MOD1 Blk(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afg.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BLK_co.paa",
			"\A3LL_Tommy\data\afg_black_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\magnoalpha_black_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgBLK_ca.paa";
	};
	class SMA_MK18afgODBLK: SMA_MK18_BASE
	{
		scope=2;
		displayName="MK18 MOD1 OD-Blk(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afg.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODblk_co.paa",
			"\A3LL_Tommy\data\afg_black_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\magnoalpha_ODBLK_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgODBLK_ca.paa";
	};
	class SMA_MK18afgBLK_SM: SMA_MK18_BASE
	{
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM Blk(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afgSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BLK_co.paa",
			"\A3LL_Tommy\data\afg_black_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\clip_diffuse3.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgBLKSM_ca.paa";
	};
	class SMA_MK18afgODBLK_SM: SMA_MK18_BASE
	{
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM OD-Blk(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afgSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODblk_co.paa",
			"\A3LL_Tommy\data\afg_black_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\clip_diffuse2.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgODBLKSM_ca.paa";
	};
	class SMA_MK18afgOD: SMA_MK18_BASE
	{
		scope=2;
		displayName="MK18 MOD1 OD(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afg.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODGRN_co.paa",
			"\A3LL_Tommy\data\afg_black_co.paa",
			"\A3LL_Tommy\data\plastic_OD_co.paa",
			"\A3LL_Tommy\data\magnoalpha_ODBLK_co.paa",
			"\A3LL_Tommy\data\sights_grn_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgOD_ca.paa";
	};
	class SMA_MK18afgOD_SM: SMA_MK18_BASE
	{
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM OD(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afgSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODGRN_co.paa",
			"\A3LL_Tommy\data\afg_black_co.paa",
			"\A3LL_Tommy\data\plastic_OD_co.paa",
			"\A3LL_Tommy\data\clip_diffuse2.paa",
			"\A3LL_Tommy\data\sights_grn_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgODSM_ca.paa";
	};
	class SMA_MK18afgTAN: SMA_MK18_BASE
	{
		scope=2;
		displayName="MK18 MOD1 Tan(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afg.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_Tan_co.paa",
			"\A3LL_Tommy\data\afg_tan_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\magnoalpha_co.paa",
			"\A3LL_Tommy\data\sights_tan_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgTAN_ca.paa";
	};
	class SMA_MK18afgTAN_SM: SMA_MK18_BASE
	{
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM Tan(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afgSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_Tan_co.paa",
			"\A3LL_Tommy\data\afg_tan_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\clip_diffuse1.paa",
			"\A3LL_Tommy\data\sights_tan_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgTANSM_ca.paa";
	};
	class SMA_MK18afgTANBLK: SMA_MK18_BASE
	{
		scope=2;
		displayName="MK18 MOD1 blk-tan(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afg.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BTan_co.paa",
			"\A3LL_Tommy\data\afg_tan_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\magnoalpha_black_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgTANBLK_ca.paa";
	};
	class SMA_MK18afgTANBLK_SM: SMA_MK18_BASE
	{
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM blk-tan(afg)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18agf.rtm"
		};
		model="\A3LL_Tommy\MK18afgSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BTan_co.paa",
			"\A3LL_Tommy\data\afg_tan_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\clip_diffuse3.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18afgTANBLKSM_ca.paa";
	};
	class SMA_MK18MOE: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		displayName="MK18 MOD1(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETan.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_co.paa",
			"\A3LL_Tommy\data\grip_blk_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\magnoalpha_black_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOE_ca.paa";
	};
	class SMA_MK18MOE_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETanSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_co.paa",
			"\A3LL_Tommy\data\grip_blk_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\clip_diffuse1.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOESM_ca.paa";
	};
	class SMA_MK18MOETAN: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		displayName="MK18 MOD1 TAN(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETan.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_Tan_co.paa",
			"\A3LL_Tommy\data\grip_Tan_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\magnoalpha_co.paa",
			"\A3LL_Tommy\data\sights_tan_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOETAN_ca.paa";
	};
	class SMA_MK18MOETAN_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM TAN(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETanSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_Tan_co.paa",
			"\A3LL_Tommy\data\grip_Tan_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\clip_diffuse1.paa",
			"\A3LL_Tommy\data\sights_tan_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOETANSM_ca.paa";
	};
	class SMA_MK18MOEBLK: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		displayName="MK18 MOD1 BLK(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETan.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BLK_co.paa",
			"\A3LL_Tommy\data\grip_blk_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\magnoalpha_black_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOEBLK_ca.paa";
	};
	class SMA_MK18MOEBLK_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM BLK(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETanSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BLK_co.paa",
			"\A3LL_Tommy\data\grip_blk_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\clip_diffuse3.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOEBLKSM_ca.paa";
	};
	class SMA_MK18MOEODBLK: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		displayName="MK18 MOD1 OD-BLK(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETan.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODblk_co.paa",
			"\A3LL_Tommy\data\grip_blk_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\magnoalpha_ODBLK_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOEODBLK_ca.paa";
	};
	class SMA_MK18MOEODBLK_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM OD-BLK(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETanSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODblk_co.paa",
			"\A3LL_Tommy\data\grip_blk_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\clip_diffuse2.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOEODBLKSM_ca.paa";
	};
	class SMA_MK18MOEOD: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		displayName="MK18 MOD1 OD(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETan.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODGRN_co.paa",
			"\A3LL_Tommy\data\grip_blk_co.paa",
			"\A3LL_Tommy\data\plastic_OD_co.paa",
			"\A3LL_Tommy\data\magnoalpha_ODBLK_co.paa",
			"\A3LL_Tommy\data\sights_grn_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOEOD_ca.paa";
	};
	class SMA_MK18MOEOD_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM OD(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETanSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODGRN_co.paa",
			"\A3LL_Tommy\data\grip_blk_co.paa",
			"\A3LL_Tommy\data\plastic_OD_co.paa",
			"\A3LL_Tommy\data\clip_diffuse2.paa",
			"\A3LL_Tommy\data\sights_grn_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOEODSM_ca.paa";
	};
	class SMA_MK18MOEBLKTAN: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		displayName="MK18 MOD1 blk-tan(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETan.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BTan_co.paa",
			"\A3LL_Tommy\data\grip_Tan_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\magnoalpha_black_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOEBLKTAN_ca.paa";
	};
	class SMA_MK18MOEBLKTAN_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=57.200001;
			class PointerSlot: PointerSlot
			{
				compatibleItems[]=
				{
					"SMA_ANPEQ15_TOP_BLK_MK18",
					"SMA_ANPEQ15_TOP_TAN_MK18",
					"SMA_SFPEQ_MK18TOP_TAN",
					"SMA_SFPEQ_MK18TOP_BLK",
					"SMA_SFPEQ_MK18TOP_TAN_LIGHT",
					"SMA_SFPEQ_MK18TOP_BLK_LIGHT"
				};
			};
			class asdg_Underbarrel
			{
				access=0;
				iconPicture="\A3\Weapons_F_Mark\Data\UI\attachment_under.paa";
				iconPinpoint="Bottom";
				iconPosition[]={0,0};
				iconScale=0;
				linkProxy="\A3\Data_F_Mark\Proxies\Weapon_Slots\UNDERBARREL";
				scope=0;
				class CompatibleItems
				{
					SMA_Gripod_01=1;
				};
			};
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		displayName="MK18 MOD1 SM blk-tan(VFG)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"A3LL_Tommy\Data\Anim\MK18moe.rtm"
		};
		model="\A3LL_Tommy\MK18MOETanSM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BTan_co.paa",
			"\A3LL_Tommy\data\grip_Tan_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\clip_diffuse3.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18MOEBLKTANSM_ca.paa";
	};
	class SMA_MK18_GL: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_co.paa",
			"\A3LL_Tommy\data\m203_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\magnoalpha_black_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18GL_ca.paa";
		displayName="MK18 MOD1(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18_GL_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203SM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_co.paa",
			"\A3LL_Tommy\data\m203_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\clip_diffuse1.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18GLSM_ca.paa";
		displayName="MK18 MOD1 SM(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18TANBLK_GL: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BTan_co.paa",
			"\A3LL_Tommy\data\m203_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\magnoalpha_black_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18TANBLKGL_ca.paa";
		displayName="MK18 MOD1 blk-tan(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18TANBLK_GL_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203SM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BTan_co.paa",
			"\A3LL_Tommy\data\m203_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\clip_diffuse3.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18TANBLKGLSM_ca.paa";
		displayName="MK18 MOD1 SM blk-tan(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18TAN_GL: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_Tan_co.paa",
			"\A3LL_Tommy\data\m203TANrough_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\magnoalpha_co.paa",
			"\A3LL_Tommy\data\sights_tan_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18TANGL_ca.paa";
		displayName="MK18 MOD1 Tan(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18TAN_GL_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203SM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_Tan_co.paa",
			"\A3LL_Tommy\data\m203TANrough_co.paa",
			"\A3LL_Tommy\data\plastic_Tan_co.paa",
			"\A3LL_Tommy\data\clip_diffuse1.paa",
			"\A3LL_Tommy\data\sights_tan_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18TANGLSM_ca.paa";
		displayName="MK18 MOD1 SM Tan(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18BLK_GL: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BLK_co.paa",
			"\A3LL_Tommy\data\m203_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\magnoalpha_black_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18BLKGL_ca.paa";
		displayName="MK18 MOD1 Blk(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18BLK_GL_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203SM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_BLK_co.paa",
			"\A3LL_Tommy\data\m203_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\clip_diffuse3.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18BLKGLSM_ca.paa";
		displayName="MK18 MOD1 SM Blk(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18ODBLK_GL: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODblk_co.paa",
			"\A3LL_Tommy\data\m203_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\magnoalpha_ODBLK_co.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18ODBLKGL_ca.paa";
		displayName="MK18 MOD1 OD-Blk(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18ODBLK_GL_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203SM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODblk_co.paa",
			"\A3LL_Tommy\data\m203_co.paa",
			"\A3LL_Tommy\data\plastic_co.paa",
			"\A3LL_Tommy\data\clip_diffuse2.paa",
			"\A3LL_Tommy\data\sights_blk_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18ODBLKGLSM_ca.paa";
		displayName="MK18 MOD1 SM OD-Blk(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18OD_GL: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODGRN_co.paa",
			"\A3LL_Tommy\data\m203ODMK18_co.paa",
			"\A3LL_Tommy\data\plastic_OD_co.paa",
			"\A3LL_Tommy\data\magnoalpha_ODBLK_co.paa",
			"\A3LL_Tommy\data\sights_grn_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18ODGL_ca.paa";
		displayName="MK18 MOD1 OD(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
	class SMA_MK18OD_GL_SM: SMA_MK18_BASE
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=100;
		};
		scope=2;
		reloadmagazinesound[]=
		{
			"A3LL_Tommy\data\MK18\ARRL4.ogg",
			1,
			1,
			35
		};
		inertia=0.51999998;
		modes[]=
		{
			"Single",
			"FullAuto"
		};
		model="\A3LL_Tommy\MK18M203SM.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3LL_Tommy\data\metal_ODGRN_co.paa",
			"\A3LL_Tommy\data\m203ODMK18_co.paa",
			"\A3LL_Tommy\data\plastic_OD_co.paa",
			"\A3LL_Tommy\data\clip_diffuse2.paa",
			"\A3LL_Tommy\data\sights_grn_co.paa"
		};
		picture="\A3LL_Tommy\ui\SMAMK18ODGLSM_ca.paa";
		displayName="MK18 MOD1 SM OD(M203)";
		author="Specialist Military Arms";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3LL_Tommy\data\Anim\M4m203.rtm"
		};
		muzzles[]=
		{
			"This",
			"EGLM"
		};
		class EGLM: UGL_F
		{
			useModelOptics=0;
			useExternalOptic=0;
			displayName="EGLM";
			descriptionShort="EGLM";
			reloadAction="GestureReloadTrgUGL";
			magazines[]=
			{
				"1Rnd_HE_Grenade_shell",
				"1Rnd_SmokeBlue_Grenade_shell",
				"1Rnd_SmokeGreen_Grenade_shell",
				"1Rnd_SmokeOrange_Grenade_shell",
				"1Rnd_SmokePurple_Grenade_shell",
				"1Rnd_SmokeRed_Grenade_shell",
				"1Rnd_Smoke_Grenade_shell",
				"1Rnd_SmokeYellow_Grenade_shell",
				"UGL_FlareYellow_F",
				"UGL_FlareWhite_F",
				"UGL_FlareRed_F",
				"UGL_FlareGreen_F",
				"UGL_FlareCIR_F"
			};
			cameraDir="OP_look";
			discreteDistance[]={100,200,300,400};
			discreteDistanceCameraPoint[]=
			{
				"OP_eye",
				"OP_eye2",
				"OP_eye3",
				"OP_eye4"
			};
			discreteDistanceInitIndex=1;
			class Single: Single
			{
				sounds[]=
				{
					"StandardSound"
				};
				class StandardSound
				{
					begin1[]=
					{
						"A3LL_Tommy\data\Launcher2",
						1.9,
						1,
						600
					};
					soundBegin[]=
					{
						"begin1",
						1
					};
					weaponSoundEffect="DefaultRifle";
				};
			};
		};
	};
};
